baseURL = "https://ramesh-rv.github.io/rvrameshdotme"
languageCode = 'en-us'
title = "Ramesh > Blog"
theme = "contrast-hugo-mod"


relativeURLS = true







[params]
   minimal = true
   excerpts = false
   description = "Ramesh's Blog"
   


[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 20
    
   
    
[[menu.main]]
    identifier = "tag"
    name = "Tags"
    url = "/tags/"
    weight = 20
       
 [[menu.main]]
    name = "GitHub"
    url = "https://github.com/ramesh-rv"
    
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/ramesh-rv-b2b57a8/"






